"""Redbud — reproducible 5-year agency model (conservative / base / aggressive).

Every input is an ASSUMPTION unless its comment cites a grade:
A = verified, B = strongly supported, C = inference/benchmark, D = speculative.
Run:  python3 model.py > output.md
"""

SCEN = {
    "conservative": dict(
        new_households=[60, 250, 700, 1500, 2800],   # D
        retention=0.80,          # C (agency benchmarks run ~80-90%)
        bundle_rate=0.20,        # D share of households that also place auto
        cac=550,                 # C realistic paid/partner blended cost per bound household
        keep_share=[0.75, 0.75, 0.80, 0.85, 0.85],   # C aggregator split, improving with direct appts
        fixed=[20_000, 100_000, 350_000, 800_000, 1_600_000],  # D non-CAC opex (team, tech, rent)
    ),
    "base": dict(
        new_households=[150, 600, 1800, 4500, 9000],  # D
        retention=0.85,          # C (Goosehead reports ~86%; B)
        bundle_rate=0.30,        # D
        cac=350,                 # C
        keep_share=[0.80, 0.80, 0.85, 0.90, 0.90],    # C
        fixed=[30_000, 150_000, 600_000, 1_600_000, 3_500_000],  # D
    ),
    "aggressive": dict(
        new_households=[250, 1200, 4000, 10000, 20000],  # D
        retention=0.88,          # C
        bundle_rate=0.40,        # D
        cac=250,                 # C (vendor cost-per-bind floor ~$120-250)
        keep_share=[0.80, 0.85, 0.90, 0.92, 0.92],    # C
        fixed=[40_000, 250_000, 1_000_000, 2_800_000, 6_000_000],  # D
    ),
}

HOME_PREMIUM = 5400      # B: OK average homeowners premium ~$5,378 (LendingTree 2026)
AUTO_PREMIUM = 2200      # D: placeholder, to be replaced with sourced OK figure
HOME_NEW, HOME_REN = 0.13, 0.10   # C: homeowners commission new 12-15%, renewal 8-12%
AUTO_NEW, AUTO_REN = 0.10, 0.09   # C
PREMIUM_INFLATION = 0.05  # D: commissions are % of premium; OK premiums rose ~7% in 2026 (B)
SERVICE_COST = 90         # D: $/policy/year servicing (CSR time, AMS seats, E&O allocation)


def run(name, s):
    rows, book = [], 0.0
    cum_cash = 0.0
    for y in range(5):
        infl = (1 + PREMIUM_INFLATION) ** y
        retained = book * s["retention"]
        new = s["new_households"][y]
        book = retained + new
        b = s["bundle_rate"]
        gross_comm = (
            new * (HOME_PREMIUM * HOME_NEW + b * AUTO_PREMIUM * AUTO_NEW)
            + retained * (HOME_PREMIUM * HOME_REN + b * AUTO_PREMIUM * AUTO_REN)
        ) * infl
        revenue = gross_comm * s["keep_share"][y]
        policies = book * (1 + b)
        service = policies * SERVICE_COST
        gross_margin = revenue - service
        acq = new * s["cac"]
        ebitda = gross_margin - acq - s["fixed"][y]
        cum_cash += ebitda
        premium_placed = book * (HOME_PREMIUM + b * AUTO_PREMIUM) * infl
        rows.append((y + 1, int(new), int(book), premium_placed, revenue, gross_margin / revenue if revenue else 0,
                     acq, ebitda, cum_cash))
    # unit economics (base-year dollars)
    b = s["bundle_rate"]
    y1 = (HOME_PREMIUM * HOME_NEW + b * AUTO_PREMIUM * AUTO_NEW) * s["keep_share"][2] - SERVICE_COST * (1 + b)
    ren = (HOME_PREMIUM * HOME_REN + b * AUTO_PREMIUM * AUTO_REN) * s["keep_share"][2] - SERVICE_COST * (1 + b)
    r = s["retention"]
    ltv = y1 + ren * r / (1 - r)          # undiscounted, no inflation (conservative on inflation)
    payback_m = 12 * s["cac"] / y1 if y1 > 0 else float("inf")
    return rows, ltv, payback_m


def fmt(x):
    return f"${x/1e6:,.2f}M" if abs(x) >= 1e6 else f"${x/1e3:,.0f}k"


print("# Redbud model output\n")
print("Generated by `model.py`. All inputs are labelled in the source; most are C/D assumptions. Not a forecast.\n")
for name, s in SCEN.items():
    rows, ltv, pb = run(name, s)
    print(f"## {name.title()}\n")
    print(f"Retention {s['retention']:.0%} · bundle {s['bundle_rate']:.0%} · CAC ${s['cac']} · "
          f"household LTV (contribution, undiscounted) ≈ ${ltv:,.0f} · LTV:CAC ≈ {ltv/s['cac']:.1f}x · "
          f"CAC payback ≈ {pb:.0f} months\n")
    print("| Year | New households | Households in force | Premium placed | Agency revenue | Gross margin | Acquisition spend | EBITDA | Cumulative cash |")
    print("|---|---|---|---|---|---|---|---|---|")
    for (y, new, book, prem, rev, gm, acq, e, cc) in rows:
        print(f"| {y} | {new:,} | {book:,} | {fmt(prem)} | {fmt(rev)} | {gm:.0%} | {fmt(acq)} | {fmt(e)} | {fmt(cc)} |")
    print()
print("## Reading the model\n")
print("- Revenue scales with *households in force × premium × commission*. Because commissions are a % of premium, "
      "premium inflation in storm states raises revenue per household without extra work (and is a political risk).")
print("- The model is most sensitive to CAC and retention. A $200 swing in CAC or 5 points of retention moves "
      "LTV:CAC more than any other input; both are measured in the 30-day and 100-day plans.")
print("- Even the aggressive case is ~$20M+ revenue in year 5. $100M revenue needs roughly $1B of premium placed "
      "(≈150k households), which is a 10+ year, multi-state outcome — see the scale path in the blueprint.")
