"""Keelson five-year operating model: conservative / base / aggressive.

Every input is an assumption (grade C/D) unless noted. Change the SCENARIOS dict and re-run:
    python3 venture/model/model.py > venture/model/output.md
Headcount is sized to ~$200-500K revenue per employee (vertical SaaS + services norm).
Revenue is booked net of duty (duty never touches our P&L; importers pay CBP directly).
"""

YEARS = 5

SCENARIOS = {
    "conservative": dict(
        new_customers=[12, 40, 90, 160, 240],
        logo_churn=0.18,
        sub_acv=[24_000, 27_000, 30_000, 33_000, 36_000],      # platform subscription per customer
        success_fee_new=12_000,                               # in-window recoveries, year of acquisition
        success_fee_existing=4_000,                           # ongoing in-window + drawback + refund events
        broker_attach=[0.0, 0.05, 0.15, 0.25, 0.30],          # share of customers filing entries through us
        broker_rev=[0, 20_000, 25_000, 30_000, 35_000],       # net brokerage revenue per attached customer
        gm_sub=0.72, gm_success=0.55, gm_broker=0.55,
        cac=14_000,
        headcount=[5, 12, 26, 48, 75],
        loaded_cost=[165_000, 175_000, 180_000, 185_000, 190_000],
        other_opex_pct=0.15,
    ),
    "base": dict(
        new_customers=[20, 70, 160, 280, 420],
        logo_churn=0.12,
        sub_acv=[30_000, 36_000, 42_000, 48_000, 54_000],
        success_fee_new=25_000,
        success_fee_existing=8_000,
        broker_attach=[0.0, 0.10, 0.25, 0.35, 0.45],
        broker_rev=[0, 30_000, 38_000, 45_000, 50_000],
        gm_sub=0.78, gm_success=0.62, gm_broker=0.62,
        cac=10_000,
        headcount=[6, 18, 45, 95, 170],
        loaded_cost=[165_000, 175_000, 180_000, 185_000, 190_000],
        other_opex_pct=0.15,
    ),
    "aggressive": dict(
        new_customers=[40, 150, 400, 750, 1_100],
        logo_churn=0.08,
        sub_acv=[36_000, 45_000, 54_000, 63_000, 72_000],
        success_fee_new=40_000,
        success_fee_existing=12_000,
        broker_attach=[0.0, 0.15, 0.35, 0.50, 0.60],
        broker_rev=[0, 40_000, 50_000, 58_000, 65_000],
        gm_sub=0.82, gm_success=0.68, gm_broker=0.70,
        cac=8_000,
        headcount=[8, 30, 85, 200, 420],
        loaded_cost=[165_000, 175_000, 180_000, 185_000, 190_000],
        other_opex_pct=0.15,
    ),
}


def run(p):
    rows, active, cash = [], 0.0, 0.0
    for y in range(YEARS):
        start = active
        new = p["new_customers"][y]
        churned = start * p["logo_churn"]
        active = start - churned + new
        avg = (start + active) / 2
        sub = avg * p["sub_acv"][y]
        success = new * p["success_fee_new"] * 0.5 + start * p["success_fee_existing"]  # new logos ~half-year of cash
        broker = avg * p["broker_attach"][y] * p["broker_rev"][y]
        revenue = sub + success + broker
        gp = sub * p["gm_sub"] + success * p["gm_success"] + broker * p["gm_broker"]
        people = p["headcount"][y] * p["loaded_cost"][y]
        s_and_m_cac = new * p["cac"]
        opex = people + s_and_m_cac + revenue * p["other_opex_pct"]
        ebitda = gp - opex
        cash += ebitda
        arr_exit = active * p["sub_acv"][y] + active * p["broker_attach"][y] * p["broker_rev"][y]
        rows.append(dict(year=y + 1, customers=round(active), new=new, revenue=revenue, arr_exit=arr_exit,
                         recurring_share=(sub + broker) / revenue, gm=gp / revenue, ebitda=ebitda,
                         cum_cash=cash, headcount=p["headcount"][y]))
    return rows


def m(x):
    return f"${x/1e6:,.1f}M"


def main():
    print("# Keelson Five-Year Model Output\n")
    print("Generated by `venture/model/model.py`. All inputs are assumptions (C/D); see script.\n")
    for name, p in SCENARIOS.items():
        rows = run(p)
        trough = min(r["cum_cash"] for r in rows)
        print(f"## {name.title()}\n")
        print("| Year | Customers (EoY) | New | Revenue | Exit ARR | Recurring % | Gross margin | EBITDA | Cumulative cash | Headcount |")
        print("|---|---|---|---|---|---|---|---|---|---|")
        for r in rows:
            print(f"| {r['year']} | {r['customers']:,} | {r['new']:,} | {m(r['revenue'])} | {m(r['arr_exit'])} | "
                  f"{r['recurring_share']:.0%} | {r['gm']:.0%} | {m(r['ebitda'])} | {m(r['cum_cash'])} | {r['headcount']} |")
        print(f"\nPeak cumulative burn (before financing): **{m(-trough) if trough < 0 else '$0'}**\n")


if __name__ == "__main__":
    main()
